server:
  port: 8080
spring:
  datasource:
    name: corpus
    url: jdbc:mysql://192.168.99.100:3307/corpus?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3308/corpus?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-wait-millis: 60000
      min-evictable-idle-time-millis: 30000
      min-idle: 1
      max-total: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
  #config: logback.xml

vendor:
  # 谷歌机器翻译api
  google-translate-url: http://translate.google.cn/translate_a/single
  # 有道词典查询api
  youdao:
    # 应用ID
    app-key: 3a18ba9a59132f54
    # 应用秘钥
    app-secret: DDPPEdDZ0yY7Jk8GABDWBeR54bVl6pkJ
    open-api-url: http://openapi.youdao.com/api
